version: "3.2"

services:
  signer:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: "signer"
    volumes:
      - type: bind
        source: ../
        target: /home/node/app
      - /home/node/app/node_modules
    networks:
      - net
    entrypoint: sh
    command: '-c "sleep 1d"'
    env_file:
      - ../.env
    ports:
      - "3000:3000"
    links:
      - mq
    depends_on:
      - mq
  mq:
    image: rabbitmq:3.9.7
    container_name: "mq"
    restart: always
    volumes:
      - type: bind
        source: ../mq/rabbitmq.conf
        target: /etc/rabbitmq/rabbitmq.conf
    networks:
      - net
networks:
  net:
