version: "3.2"

services:
  signer:
    image: blocklords/smartcontract-signer:1.0.0
    container_name: "signer"
    volumes:
      - type: bind 
        source: ../private
        target: /home/node/app/private
    networks:
      - net
    env_file:
      - ../.env
    ports:
      - "3000:3000"
    links:
      - mq
    depends_on:
      - mq
  mq:
    image: rabbitmq:3.9.7
    container_name: "mq"
    restart: always
    volumes:
      - type: bind
        source: ../mq/rabbitmq.conf
        target: /etc/rabbitmq/rabbitmq.conf
    networks:
      - net
networks:
  net:
